静的解析ツールrubocopを追加
k-kudo-hub/error_note_sample pull request #33
Opened 2021-04-25 09:27 UTC by toshiro-koba

# やったこと
- rubocop周りのgemをインストール
- .rubocop.ymlを設定
- `rubocop -A`など実行して既存コードを整形
- 既存機能を今まで通り使えることを確認しました

## 覚書
`.rubocop.yml`の記述は9割強コピペです笑
これ必要、不要とかあれば随時修正していきましょ！

そしてrubocop実行したのでファイルいっぱい整形されてます🙇
`bundle install`もお願いします

## 追加したgem
- rubocop
- rubocop-performance
- rubocop-rails
- rubocop-rspec

参考にした記事
[【Rails】RuboCop 導入編（2020年10月版） - Qiita](https://qiita.com/piggydev/items/074e020e07af7ebc872d)

2021-04-25 10:10 UTC, k-kudo-hub requested changes
rubocopの導入ありがとう！
こちらの見過ごしだったら申し訳ないんだけど、rubocop導入に関するissueってあったっけ？
rubocopの利便性は理解しているつもりなんだけど、コード全体に影響するツールだけに、せめて導入のタイミングについては議論しておきたかったなと思っています。（もしそういう具体的な話をしてたとしたらこちらが忘れてるので大変申し訳ない🙏）

このPRについては一旦Draftにして、機能等が揃ったタイミングで整形を行うことを提案させてください。せっかくやってもらったのに申し訳ない🙇‍♂️

2021-04-25 11:07 UTC, toshiro-koba commented
> rubocopの導入ありがとう！
> こちらの見過ごしだったら申し訳ないんだけど、rubocop導入に関するissueってあったっけ？
> rubocopの利便性は理解しているつもりなんだけど、コード全体に影響するツールだけに、せめて導入のタイミングについては議論しておきたかったなと思っています。（もしそういう具体的な話をしてたとしたらこちらが忘れてるので大変申し訳ない🙏）
> 
> このPRについては一旦Draftにして、機能等が揃ったタイミングで整形を行うことを提案させてください。せっかくやってもらったのに申し訳ない🙇‍♂️

ごめん！issue立ててなかった！
issueで互いに同意してからPR→実装という認識が欠けてました💦
導入時期はのちほど相談しましょ！
一旦Draftにします。

2021-05-06 11:21 UTC, k-kudo-hub commented
@toshiro-koba 
結構なコンフリクトが起きているので、工程を1からなぞってもらった方が早いかもしれない🙏

2021-05-06 12:14 UTC, toshiro-koba commented
conflictの解消のさせ方が分からない😅
PR作り直そうかな

2021-05-06 12:17 UTC, k-kudo-hub commented
うーん、そのほうが早いかもね💦
申し訳ないけどよろしくお願いします🙏

2021-05-06 12:43 UTC, toshiro-koba commented
解消できたー！

今回はrubocopは回せてないです笑
rubocop実行するとconfilictなっちゃうので😅

2021-05-06 12:49 UTC, merged

2021-05-06 12:51 UTC, k-kudo-hub commented
うおおさすが！🔥
こちらも動作確認完了しました！（LGTM！って言わせて笑）
できれば次回以降これやってからプッシュしてね的なコマンドがあればご教授いただきたい

2021-05-06 12:53 UTC, toshiro-koba commented
ごめん勝手にmergeしてしまった😅申し訳ない🙏

2021-05-06 12:54 UTC, k-kudo-hub commented
びっくりしたけど大丈夫！笑

2021-05-06 12:58 UTC, k-kudo-hub commented
コマンドは`rubocop -A` でよかったっけ？

2021-05-06 13:01 UTC, toshiro-koba commented
そうだね。
`rubocop -A`でだいたい整形する。

残った警告は手動で整形するか、.rubocop.ymlのルールを変更するかかな。

2021-05-06 13:48 UTC, k-kudo-hub commented
了解した！ありがとう🙏
細かいルールについてはMTGで詰めましょう